apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  namespace: default
  labels:
    component: elasticsearch
    clustername: proofofconcept
spec:
  replicas: 1
  selector:
    component: elasticsearch
    clustername: proofofconcept
  template:
    metadata:
      labels:
        component: elasticsearch
        clustername: proofofconcept
    spec:
      serviceAccount: elasticsearch
      containers:
      - name: elasticsearch
        image: combor/elasticsearch-kubernetes:latest
        env:
        - name: KUBERNETES_TRUST_CERT
          value: "true"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        source:
          emptyDir: {}
